
const mongoose = require("mongoose");

const loanSchema = new mongoose.Schema(
  {
    // =====================================================
    // RELATIONSHIPS
    // =====================================================

    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    loanOffer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "LoanOffer",
      required: true,
      unique: true,
      index: true,
    },

    loanApplication: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "LoanApplication",
      required: true,
      index: true,
    },

    loanProduct: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "LoanProduct",
      required: true,
      index: true,
    },

    // Repayment schedule is created when disbursement succeeds.
    // It is optional because a loan can exist before disbursement.
    repaymentSchedule: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "RepaymentSchedule",
      default: null,
      index: true,
    },

    mandate: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Mandate",
      default: null,
    },

    // =====================================================
    // LOAN IDENTIFICATION
    // =====================================================

    loanNumber: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    // =====================================================
    // FINANCIAL DETAILS
    // =====================================================

    principalAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    interestAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    feeAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    totalRepayment: {
      type: Number,
      required: true,
      min: 0,
    },

    amountDisbursed: {
      type: Number,
      default: 0,
      min: 0,
    },

    amountPaid: {
      type: Number,
      default: 0,
      min: 0,
    },

    outstandingAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    interestRate: {
      type: Number,
      required: true,
      min: 0,
    },

    interestType: {
      type: String,
      enum: ["flat", "reducing_balance"],
      required: true,
    },

    // =====================================================
    // REPAYMENT TERMS
    // =====================================================

    durationDays: {
      type: Number,
      required: true,
      min: 1,
    },

    repaymentFrequency: {
      type: String,
      enum: [
        "daily",
        "weekly",
        "biweekly",
        "monthly",
      ],
      required: true,
    },

    numberOfInstallments: {
      type: Number,
      required: true,
      min: 1,
    },

    installmentAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    // =====================================================
    // LOAN STATUS
    // =====================================================

    status: {
      type: String,
      enum: [
        "pending_disbursement",
        "disbursing",
        "active",
        "completed",
        "overdue",
        "defaulted",
        "cancelled",
      ],
      default: "pending_disbursement",
      index: true,
    },

    // =====================================================
    // DISBURSEMENT
    // =====================================================

    /*
     * Determines how this loan will be disbursed.
     *
     * paystack:
     *   System sends the money through Paystack.
     *
     * manual:
     *   Admin sends the money externally and records
     *   the transaction reference.
     */
    disbursementMethod: {
      type: String,
      enum: ["manual", "paystack"],
      default: "paystack",
      index: true,
    },

    /*
     * Current state of the disbursement process.
     *
     * PENDING:
     *   Loan is ready for disbursement.
     *
     * PROCESSING:
     *   A disbursement method has claimed the loan.
     *
     * SUCCESS:
     *   Customer has been successfully disbursed.
     *
     * FAILED:
     *   Disbursement attempt failed.
     *
     * REVERSED:
     *   Previously successful Paystack transfer was reversed.
     */
    disbursementStatus: {
      type: String,
      enum: [
        "PENDING",
        "PROCESSING",
        "SUCCESS",
        "FAILED",
        "REVERSED",
      ],
      default: "PENDING",
      index: true,
    },

    /*
     * Internal or external disbursement reference.
     *
     * For Paystack this can be the Paystack/reference ID
     * generated by the system.
     *
     * For manual disbursement this can be the bank/payment
     * transaction reference entered by the admin.
     */
    disbursementReference: {
      type: String,
      default: null,
      sparse: true,
      index: true,
      trim: true,
    },

    /*
     * Admin-generated/manual transfer reference.
     *
     * Kept separately for audit purposes when the admin
     * completes an external/manual payment.
     */
    manualDisbursementReference: {
      type: String,
      default: null,
      trim: true,
    },

    /*
     * Admin who initiated or completed a manual
     * disbursement.
     */
    disbursedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },

    // =====================================================
    // PAYSTACK DISBURSEMENT DETAILS
    // =====================================================

    paystackTransferCode: {
      type: String,
      default: null,
      trim: true,
      index: true,
    },

    paystackTransferId: {
      type: String,
      default: null,
      trim: true,
      index: true,
    },

    // =====================================================
    // DISBURSEMENT AUDIT / REASON
    // =====================================================

    disbursementReason: {
      type: String,
      default: null,
      trim: true,
      maxlength: 500,
    },

    // =====================================================
    // DATES
    // =====================================================

    disbursedAt: {
      type: Date,
      default: null,
    },

    startDate: {
      type: Date,
      default: null,
    },

    maturityDate: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  },
);

// =====================================================
// INDEXES
// =====================================================

loanSchema.index({
  user: 1,
  status: 1,
});

loanSchema.index({
  user: 1,
  createdAt: -1,
});

loanSchema.index({
  disbursementMethod: 1,
  disbursementStatus: 1,
});

// =====================================================
// MODEL
// =====================================================

module.exports =
  mongoose.models.Loan ||
  mongoose.model("Loan", loanSchema);
